// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.6.1
// source: internal/clients/availability/pb/availability.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AvailabilityService_HoldSlot_FullMethodName           = "/availability.AvailabilityService/HoldSlot"
	AvailabilityService_ConfirmSlotBooking_FullMethodName = "/availability.AvailabilityService/ConfirmSlotBooking"
	AvailabilityService_ReleaseHeldSlot_FullMethodName    = "/availability.AvailabilityService/ReleaseHeldSlot"
)

// AvailabilityServiceClient is the client API for AvailabilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AvailabilityServiceClient interface {
	HoldSlot(ctx context.Context, in *HoldSlotRequest, opts ...grpc.CallOption) (*HoldSlotResponse, error)
	ConfirmSlotBooking(ctx context.Context, in *ConfirmSlotBookingRequest, opts ...grpc.CallOption) (*ConfirmSlotBookingResponse, error)
	ReleaseHeldSlot(ctx context.Context, in *ReleaseHeldSlotRequest, opts ...grpc.CallOption) (*ReleaseHeldSlotResponse, error)
}

type availabilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAvailabilityServiceClient(cc grpc.ClientConnInterface) AvailabilityServiceClient {
	return &availabilityServiceClient{cc}
}

func (c *availabilityServiceClient) HoldSlot(ctx context.Context, in *HoldSlotRequest, opts ...grpc.CallOption) (*HoldSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HoldSlotResponse)
	err := c.cc.Invoke(ctx, AvailabilityService_HoldSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *availabilityServiceClient) ConfirmSlotBooking(ctx context.Context, in *ConfirmSlotBookingRequest, opts ...grpc.CallOption) (*ConfirmSlotBookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmSlotBookingResponse)
	err := c.cc.Invoke(ctx, AvailabilityService_ConfirmSlotBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *availabilityServiceClient) ReleaseHeldSlot(ctx context.Context, in *ReleaseHeldSlotRequest, opts ...grpc.CallOption) (*ReleaseHeldSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseHeldSlotResponse)
	err := c.cc.Invoke(ctx, AvailabilityService_ReleaseHeldSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AvailabilityServiceServer is the server API for AvailabilityService service.
// All implementations must embed UnimplementedAvailabilityServiceServer
// for forward compatibility.
type AvailabilityServiceServer interface {
	HoldSlot(context.Context, *HoldSlotRequest) (*HoldSlotResponse, error)
	ConfirmSlotBooking(context.Context, *ConfirmSlotBookingRequest) (*ConfirmSlotBookingResponse, error)
	ReleaseHeldSlot(context.Context, *ReleaseHeldSlotRequest) (*ReleaseHeldSlotResponse, error)
	mustEmbedUnimplementedAvailabilityServiceServer()
}

// UnimplementedAvailabilityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAvailabilityServiceServer struct{}

func (UnimplementedAvailabilityServiceServer) HoldSlot(context.Context, *HoldSlotRequest) (*HoldSlotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HoldSlot not implemented")
}
func (UnimplementedAvailabilityServiceServer) ConfirmSlotBooking(context.Context, *ConfirmSlotBookingRequest) (*ConfirmSlotBookingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmSlotBooking not implemented")
}
func (UnimplementedAvailabilityServiceServer) ReleaseHeldSlot(context.Context, *ReleaseHeldSlotRequest) (*ReleaseHeldSlotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseHeldSlot not implemented")
}
func (UnimplementedAvailabilityServiceServer) mustEmbedUnimplementedAvailabilityServiceServer() {}
func (UnimplementedAvailabilityServiceServer) testEmbeddedByValue()                             {}

// UnsafeAvailabilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AvailabilityServiceServer will
// result in compilation errors.
type UnsafeAvailabilityServiceServer interface {
	mustEmbedUnimplementedAvailabilityServiceServer()
}

func RegisterAvailabilityServiceServer(s grpc.ServiceRegistrar, srv AvailabilityServiceServer) {
	// If the following call panics, it indicates UnimplementedAvailabilityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AvailabilityService_ServiceDesc, srv)
}

func _AvailabilityService_HoldSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HoldSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvailabilityServiceServer).HoldSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvailabilityService_HoldSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvailabilityServiceServer).HoldSlot(ctx, req.(*HoldSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvailabilityService_ConfirmSlotBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmSlotBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvailabilityServiceServer).ConfirmSlotBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvailabilityService_ConfirmSlotBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvailabilityServiceServer).ConfirmSlotBooking(ctx, req.(*ConfirmSlotBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvailabilityService_ReleaseHeldSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseHeldSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvailabilityServiceServer).ReleaseHeldSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvailabilityService_ReleaseHeldSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvailabilityServiceServer).ReleaseHeldSlot(ctx, req.(*ReleaseHeldSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AvailabilityService_ServiceDesc is the grpc.ServiceDesc for AvailabilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AvailabilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "availability.AvailabilityService",
	HandlerType: (*AvailabilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HoldSlot",
			Handler:    _AvailabilityService_HoldSlot_Handler,
		},
		{
			MethodName: "ConfirmSlotBooking",
			Handler:    _AvailabilityService_ConfirmSlotBooking_Handler,
		},
		{
			MethodName: "ReleaseHeldSlot",
			Handler:    _AvailabilityService_ReleaseHeldSlot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/clients/availability/pb/availability.proto",
}
