// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: internal/clients/availability/pb/availability.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HoldSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	BookingId     string                 `protobuf:"bytes,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	HeldUntil     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=held_until,json=heldUntil,proto3" json:"held_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldSlotRequest) Reset() {
	*x = HoldSlotRequest{}
	mi := &file_internal_clients_availability_pb_availability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldSlotRequest) ProtoMessage() {}

func (x *HoldSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clients_availability_pb_availability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldSlotRequest.ProtoReflect.Descriptor instead.
func (*HoldSlotRequest) Descriptor() ([]byte, []int) {
	return file_internal_clients_availability_pb_availability_proto_rawDescGZIP(), []int{0}
}

func (x *HoldSlotRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *HoldSlotRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *HoldSlotRequest) GetHeldUntil() *timestamp.Timestamp {
	if x != nil {
		return x.HeldUntil
	}
	return nil
}

type HoldSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	HeldUntil     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=held_until,json=heldUntil,proto3" json:"held_until,omitempty"`
	BookingId     string                 `protobuf:"bytes,4,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldSlotResponse) Reset() {
	*x = HoldSlotResponse{}
	mi := &file_internal_clients_availability_pb_availability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldSlotResponse) ProtoMessage() {}

func (x *HoldSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clients_availability_pb_availability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldSlotResponse.ProtoReflect.Descriptor instead.
func (*HoldSlotResponse) Descriptor() ([]byte, []int) {
	return file_internal_clients_availability_pb_availability_proto_rawDescGZIP(), []int{1}
}

func (x *HoldSlotResponse) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *HoldSlotResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HoldSlotResponse) GetHeldUntil() *timestamp.Timestamp {
	if x != nil {
		return x.HeldUntil
	}
	return nil
}

func (x *HoldSlotResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type ConfirmSlotBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	BookingId     string                 `protobuf:"bytes,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmSlotBookingRequest) Reset() {
	*x = ConfirmSlotBookingRequest{}
	mi := &file_internal_clients_availability_pb_availability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmSlotBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmSlotBookingRequest) ProtoMessage() {}

func (x *ConfirmSlotBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clients_availability_pb_availability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmSlotBookingRequest.ProtoReflect.Descriptor instead.
func (*ConfirmSlotBookingRequest) Descriptor() ([]byte, []int) {
	return file_internal_clients_availability_pb_availability_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmSlotBookingRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *ConfirmSlotBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type ConfirmSlotBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	BookingId     string                 `protobuf:"bytes,3,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmSlotBookingResponse) Reset() {
	*x = ConfirmSlotBookingResponse{}
	mi := &file_internal_clients_availability_pb_availability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmSlotBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmSlotBookingResponse) ProtoMessage() {}

func (x *ConfirmSlotBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clients_availability_pb_availability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmSlotBookingResponse.ProtoReflect.Descriptor instead.
func (*ConfirmSlotBookingResponse) Descriptor() ([]byte, []int) {
	return file_internal_clients_availability_pb_availability_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmSlotBookingResponse) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *ConfirmSlotBookingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConfirmSlotBookingResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type ReleaseHeldSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	BookingId     string                 `protobuf:"bytes,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseHeldSlotRequest) Reset() {
	*x = ReleaseHeldSlotRequest{}
	mi := &file_internal_clients_availability_pb_availability_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseHeldSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseHeldSlotRequest) ProtoMessage() {}

func (x *ReleaseHeldSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clients_availability_pb_availability_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseHeldSlotRequest.ProtoReflect.Descriptor instead.
func (*ReleaseHeldSlotRequest) Descriptor() ([]byte, []int) {
	return file_internal_clients_availability_pb_availability_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseHeldSlotRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *ReleaseHeldSlotRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type ReleaseHeldSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseHeldSlotResponse) Reset() {
	*x = ReleaseHeldSlotResponse{}
	mi := &file_internal_clients_availability_pb_availability_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseHeldSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseHeldSlotResponse) ProtoMessage() {}

func (x *ReleaseHeldSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clients_availability_pb_availability_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseHeldSlotResponse.ProtoReflect.Descriptor instead.
func (*ReleaseHeldSlotResponse) Descriptor() ([]byte, []int) {
	return file_internal_clients_availability_pb_availability_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseHeldSlotResponse) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *ReleaseHeldSlotResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_internal_clients_availability_pb_availability_proto protoreflect.FileDescriptor

const file_internal_clients_availability_pb_availability_proto_rawDesc = "" +
	"\n" +
	"3internal/clients/availability/pb/availability.proto\x12\favailability\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x01\n" +
	"\x0fHoldSlotRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\tR\tbookingId\x129\n" +
	"\n" +
	"held_until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\theldUntil\"\x9d\x01\n" +
	"\x10HoldSlotResponse\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"held_until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\theldUntil\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x04 \x01(\tR\tbookingId\"S\n" +
	"\x19ConfirmSlotBookingRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\tR\tbookingId\"l\n" +
	"\x1aConfirmSlotBookingResponse\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x03 \x01(\tR\tbookingId\"P\n" +
	"\x16ReleaseHeldSlotRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\tR\tbookingId\"J\n" +
	"\x17ReleaseHeldSlotResponse\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xa9\x02\n" +
	"\x13AvailabilityService\x12I\n" +
	"\bHoldSlot\x12\x1d.availability.HoldSlotRequest\x1a\x1e.availability.HoldSlotResponse\x12g\n" +
	"\x12ConfirmSlotBooking\x12'.availability.ConfirmSlotBookingRequest\x1a(.availability.ConfirmSlotBookingResponse\x12^\n" +
	"\x0fReleaseHeldSlot\x12$.availability.ReleaseHeldSlotRequest\x1a%.availability.ReleaseHeldSlotResponseBHZFgithub.com/MedConnect/booking-service/internal/clients/availability/pbb\x06proto3"

var (
	file_internal_clients_availability_pb_availability_proto_rawDescOnce sync.Once
	file_internal_clients_availability_pb_availability_proto_rawDescData []byte
)

func file_internal_clients_availability_pb_availability_proto_rawDescGZIP() []byte {
	file_internal_clients_availability_pb_availability_proto_rawDescOnce.Do(func() {
		file_internal_clients_availability_pb_availability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_clients_availability_pb_availability_proto_rawDesc), len(file_internal_clients_availability_pb_availability_proto_rawDesc)))
	})
	return file_internal_clients_availability_pb_availability_proto_rawDescData
}

var file_internal_clients_availability_pb_availability_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_clients_availability_pb_availability_proto_goTypes = []any{
	(*HoldSlotRequest)(nil),            // 0: availability.HoldSlotRequest
	(*HoldSlotResponse)(nil),           // 1: availability.HoldSlotResponse
	(*ConfirmSlotBookingRequest)(nil),  // 2: availability.ConfirmSlotBookingRequest
	(*ConfirmSlotBookingResponse)(nil), // 3: availability.ConfirmSlotBookingResponse
	(*ReleaseHeldSlotRequest)(nil),     // 4: availability.ReleaseHeldSlotRequest
	(*ReleaseHeldSlotResponse)(nil),    // 5: availability.ReleaseHeldSlotResponse
	(*timestamp.Timestamp)(nil),        // 6: google.protobuf.Timestamp
}
var file_internal_clients_availability_pb_availability_proto_depIdxs = []int32{
	6, // 0: availability.HoldSlotRequest.held_until:type_name -> google.protobuf.Timestamp
	6, // 1: availability.HoldSlotResponse.held_until:type_name -> google.protobuf.Timestamp
	0, // 2: availability.AvailabilityService.HoldSlot:input_type -> availability.HoldSlotRequest
	2, // 3: availability.AvailabilityService.ConfirmSlotBooking:input_type -> availability.ConfirmSlotBookingRequest
	4, // 4: availability.AvailabilityService.ReleaseHeldSlot:input_type -> availability.ReleaseHeldSlotRequest
	1, // 5: availability.AvailabilityService.HoldSlot:output_type -> availability.HoldSlotResponse
	3, // 6: availability.AvailabilityService.ConfirmSlotBooking:output_type -> availability.ConfirmSlotBookingResponse
	5, // 7: availability.AvailabilityService.ReleaseHeldSlot:output_type -> availability.ReleaseHeldSlotResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_clients_availability_pb_availability_proto_init() }
func file_internal_clients_availability_pb_availability_proto_init() {
	if File_internal_clients_availability_pb_availability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_clients_availability_pb_availability_proto_rawDesc), len(file_internal_clients_availability_pb_availability_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_clients_availability_pb_availability_proto_goTypes,
		DependencyIndexes: file_internal_clients_availability_pb_availability_proto_depIdxs,
		MessageInfos:      file_internal_clients_availability_pb_availability_proto_msgTypes,
	}.Build()
	File_internal_clients_availability_pb_availability_proto = out.File
	file_internal_clients_availability_pb_availability_proto_goTypes = nil
	file_internal_clients_availability_pb_availability_proto_depIdxs = nil
}
