// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pb/availability.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Slot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	DoctorId      string                 `protobuf:"bytes,2,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Specialty     string                 `protobuf:"bytes,3,opt,name=specialty,proto3" json:"specialty,omitempty"`
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slot) Reset() {
	*x = Slot{}
	mi := &file_pb_availability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_pb_availability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_pb_availability_proto_rawDescGZIP(), []int{0}
}

func (x *Slot) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *Slot) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *Slot) GetSpecialty() string {
	if x != nil {
		return x.Specialty
	}
	return ""
}

func (x *Slot) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Slot) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Slot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetAvailableSlotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Specialty     string                 `protobuf:"bytes,1,opt,name=specialty,proto3" json:"specialty,omitempty"`
	FromDate      string                 `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        string                 `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	DoctorId      string                 `protobuf:"bytes,4,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableSlotsRequest) Reset() {
	*x = GetAvailableSlotsRequest{}
	mi := &file_pb_availability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableSlotsRequest) ProtoMessage() {}

func (x *GetAvailableSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_availability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableSlotsRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableSlotsRequest) Descriptor() ([]byte, []int) {
	return file_pb_availability_proto_rawDescGZIP(), []int{1}
}

func (x *GetAvailableSlotsRequest) GetSpecialty() string {
	if x != nil {
		return x.Specialty
	}
	return ""
}

func (x *GetAvailableSlotsRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *GetAvailableSlotsRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

func (x *GetAvailableSlotsRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

type GetAvailableSlotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*Slot                `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableSlotsResponse) Reset() {
	*x = GetAvailableSlotsResponse{}
	mi := &file_pb_availability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableSlotsResponse) ProtoMessage() {}

func (x *GetAvailableSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_availability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableSlotsResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableSlotsResponse) Descriptor() ([]byte, []int) {
	return file_pb_availability_proto_rawDescGZIP(), []int{2}
}

func (x *GetAvailableSlotsResponse) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type HoldSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	BookingId     string                 `protobuf:"bytes,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	HeldUntil     string                 `protobuf:"bytes,3,opt,name=held_until,json=heldUntil,proto3" json:"held_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldSlotRequest) Reset() {
	*x = HoldSlotRequest{}
	mi := &file_pb_availability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldSlotRequest) ProtoMessage() {}

func (x *HoldSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_availability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldSlotRequest.ProtoReflect.Descriptor instead.
func (*HoldSlotRequest) Descriptor() ([]byte, []int) {
	return file_pb_availability_proto_rawDescGZIP(), []int{3}
}

func (x *HoldSlotRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *HoldSlotRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *HoldSlotRequest) GetHeldUntil() string {
	if x != nil {
		return x.HeldUntil
	}
	return ""
}

type HoldSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	HeldUntil     string                 `protobuf:"bytes,3,opt,name=held_until,json=heldUntil,proto3" json:"held_until,omitempty"`
	BookingId     string                 `protobuf:"bytes,4,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldSlotResponse) Reset() {
	*x = HoldSlotResponse{}
	mi := &file_pb_availability_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldSlotResponse) ProtoMessage() {}

func (x *HoldSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_availability_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldSlotResponse.ProtoReflect.Descriptor instead.
func (*HoldSlotResponse) Descriptor() ([]byte, []int) {
	return file_pb_availability_proto_rawDescGZIP(), []int{4}
}

func (x *HoldSlotResponse) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *HoldSlotResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HoldSlotResponse) GetHeldUntil() string {
	if x != nil {
		return x.HeldUntil
	}
	return ""
}

func (x *HoldSlotResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type ConfirmSlotBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	BookingId     string                 `protobuf:"bytes,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmSlotBookingRequest) Reset() {
	*x = ConfirmSlotBookingRequest{}
	mi := &file_pb_availability_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmSlotBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmSlotBookingRequest) ProtoMessage() {}

func (x *ConfirmSlotBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_availability_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmSlotBookingRequest.ProtoReflect.Descriptor instead.
func (*ConfirmSlotBookingRequest) Descriptor() ([]byte, []int) {
	return file_pb_availability_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmSlotBookingRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *ConfirmSlotBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type ConfirmSlotBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	BookingId     string                 `protobuf:"bytes,3,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmSlotBookingResponse) Reset() {
	*x = ConfirmSlotBookingResponse{}
	mi := &file_pb_availability_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmSlotBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmSlotBookingResponse) ProtoMessage() {}

func (x *ConfirmSlotBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_availability_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmSlotBookingResponse.ProtoReflect.Descriptor instead.
func (*ConfirmSlotBookingResponse) Descriptor() ([]byte, []int) {
	return file_pb_availability_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmSlotBookingResponse) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *ConfirmSlotBookingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConfirmSlotBookingResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type ReleaseHeldSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	BookingId     string                 `protobuf:"bytes,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseHeldSlotRequest) Reset() {
	*x = ReleaseHeldSlotRequest{}
	mi := &file_pb_availability_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseHeldSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseHeldSlotRequest) ProtoMessage() {}

func (x *ReleaseHeldSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_availability_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseHeldSlotRequest.ProtoReflect.Descriptor instead.
func (*ReleaseHeldSlotRequest) Descriptor() ([]byte, []int) {
	return file_pb_availability_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseHeldSlotRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *ReleaseHeldSlotRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type ReleaseHeldSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseHeldSlotResponse) Reset() {
	*x = ReleaseHeldSlotResponse{}
	mi := &file_pb_availability_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseHeldSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseHeldSlotResponse) ProtoMessage() {}

func (x *ReleaseHeldSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_availability_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseHeldSlotResponse.ProtoReflect.Descriptor instead.
func (*ReleaseHeldSlotResponse) Descriptor() ([]byte, []int) {
	return file_pb_availability_proto_rawDescGZIP(), []int{8}
}

func (x *ReleaseHeldSlotResponse) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *ReleaseHeldSlotResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetDoctorAgendaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      string                 `protobuf:"bytes,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	FromDate      string                 `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        string                 `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDoctorAgendaRequest) Reset() {
	*x = GetDoctorAgendaRequest{}
	mi := &file_pb_availability_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoctorAgendaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorAgendaRequest) ProtoMessage() {}

func (x *GetDoctorAgendaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_availability_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorAgendaRequest.ProtoReflect.Descriptor instead.
func (*GetDoctorAgendaRequest) Descriptor() ([]byte, []int) {
	return file_pb_availability_proto_rawDescGZIP(), []int{9}
}

func (x *GetDoctorAgendaRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *GetDoctorAgendaRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *GetDoctorAgendaRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

type GetDoctorAgendaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      string                 `protobuf:"bytes,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Slots         []*Slot                `protobuf:"bytes,2,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDoctorAgendaResponse) Reset() {
	*x = GetDoctorAgendaResponse{}
	mi := &file_pb_availability_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoctorAgendaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorAgendaResponse) ProtoMessage() {}

func (x *GetDoctorAgendaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_availability_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorAgendaResponse.ProtoReflect.Descriptor instead.
func (*GetDoctorAgendaResponse) Descriptor() ([]byte, []int) {
	return file_pb_availability_proto_rawDescGZIP(), []int{10}
}

func (x *GetDoctorAgendaResponse) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *GetDoctorAgendaResponse) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

var File_pb_availability_proto protoreflect.FileDescriptor

const file_pb_availability_proto_rawDesc = "" +
	"\n" +
	"\x15pb/availability.proto\x12\favailability\"\xac\x01\n" +
	"\x04Slot\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x1b\n" +
	"\tdoctor_id\x18\x02 \x01(\tR\bdoctorId\x12\x1c\n" +
	"\tspecialty\x18\x03 \x01(\tR\tspecialty\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x8b\x01\n" +
	"\x18GetAvailableSlotsRequest\x12\x1c\n" +
	"\tspecialty\x18\x01 \x01(\tR\tspecialty\x12\x1b\n" +
	"\tfrom_date\x18\x02 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x03 \x01(\tR\x06toDate\x12\x1b\n" +
	"\tdoctor_id\x18\x04 \x01(\tR\bdoctorId\"E\n" +
	"\x19GetAvailableSlotsResponse\x12(\n" +
	"\x05slots\x18\x01 \x03(\v2\x12.availability.SlotR\x05slots\"h\n" +
	"\x0fHoldSlotRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\tR\tbookingId\x12\x1d\n" +
	"\n" +
	"held_until\x18\x03 \x01(\tR\theldUntil\"\x81\x01\n" +
	"\x10HoldSlotResponse\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"held_until\x18\x03 \x01(\tR\theldUntil\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x04 \x01(\tR\tbookingId\"S\n" +
	"\x19ConfirmSlotBookingRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\tR\tbookingId\"l\n" +
	"\x1aConfirmSlotBookingResponse\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x03 \x01(\tR\tbookingId\"P\n" +
	"\x16ReleaseHeldSlotRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\tR\tbookingId\"J\n" +
	"\x17ReleaseHeldSlotResponse\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"k\n" +
	"\x16GetDoctorAgendaRequest\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\tR\bdoctorId\x12\x1b\n" +
	"\tfrom_date\x18\x02 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x03 \x01(\tR\x06toDate\"`\n" +
	"\x17GetDoctorAgendaResponse\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\tR\bdoctorId\x12(\n" +
	"\x05slots\x18\x02 \x03(\v2\x12.availability.SlotR\x05slots2\xef\x03\n" +
	"\x13AvailabilityService\x12d\n" +
	"\x11GetAvailableSlots\x12&.availability.GetAvailableSlotsRequest\x1a'.availability.GetAvailableSlotsResponse\x12I\n" +
	"\bHoldSlot\x12\x1d.availability.HoldSlotRequest\x1a\x1e.availability.HoldSlotResponse\x12g\n" +
	"\x12ConfirmSlotBooking\x12'.availability.ConfirmSlotBookingRequest\x1a(.availability.ConfirmSlotBookingResponse\x12^\n" +
	"\x0fReleaseHeldSlot\x12$.availability.ReleaseHeldSlotRequest\x1a%.availability.ReleaseHeldSlotResponse\x12^\n" +
	"\x0fGetDoctorAgenda\x12$.availability.GetDoctorAgendaRequest\x1a%.availability.GetDoctorAgendaResponseB:Z8github.com/Carlos-JPS/medconnect/availability-service/pbb\x06proto3"

var (
	file_pb_availability_proto_rawDescOnce sync.Once
	file_pb_availability_proto_rawDescData []byte
)

func file_pb_availability_proto_rawDescGZIP() []byte {
	file_pb_availability_proto_rawDescOnce.Do(func() {
		file_pb_availability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_availability_proto_rawDesc), len(file_pb_availability_proto_rawDesc)))
	})
	return file_pb_availability_proto_rawDescData
}

var file_pb_availability_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pb_availability_proto_goTypes = []any{
	(*Slot)(nil),                       // 0: availability.Slot
	(*GetAvailableSlotsRequest)(nil),   // 1: availability.GetAvailableSlotsRequest
	(*GetAvailableSlotsResponse)(nil),  // 2: availability.GetAvailableSlotsResponse
	(*HoldSlotRequest)(nil),            // 3: availability.HoldSlotRequest
	(*HoldSlotResponse)(nil),           // 4: availability.HoldSlotResponse
	(*ConfirmSlotBookingRequest)(nil),  // 5: availability.ConfirmSlotBookingRequest
	(*ConfirmSlotBookingResponse)(nil), // 6: availability.ConfirmSlotBookingResponse
	(*ReleaseHeldSlotRequest)(nil),     // 7: availability.ReleaseHeldSlotRequest
	(*ReleaseHeldSlotResponse)(nil),    // 8: availability.ReleaseHeldSlotResponse
	(*GetDoctorAgendaRequest)(nil),     // 9: availability.GetDoctorAgendaRequest
	(*GetDoctorAgendaResponse)(nil),    // 10: availability.GetDoctorAgendaResponse
}
var file_pb_availability_proto_depIdxs = []int32{
	0,  // 0: availability.GetAvailableSlotsResponse.slots:type_name -> availability.Slot
	0,  // 1: availability.GetDoctorAgendaResponse.slots:type_name -> availability.Slot
	1,  // 2: availability.AvailabilityService.GetAvailableSlots:input_type -> availability.GetAvailableSlotsRequest
	3,  // 3: availability.AvailabilityService.HoldSlot:input_type -> availability.HoldSlotRequest
	5,  // 4: availability.AvailabilityService.ConfirmSlotBooking:input_type -> availability.ConfirmSlotBookingRequest
	7,  // 5: availability.AvailabilityService.ReleaseHeldSlot:input_type -> availability.ReleaseHeldSlotRequest
	9,  // 6: availability.AvailabilityService.GetDoctorAgenda:input_type -> availability.GetDoctorAgendaRequest
	2,  // 7: availability.AvailabilityService.GetAvailableSlots:output_type -> availability.GetAvailableSlotsResponse
	4,  // 8: availability.AvailabilityService.HoldSlot:output_type -> availability.HoldSlotResponse
	6,  // 9: availability.AvailabilityService.ConfirmSlotBooking:output_type -> availability.ConfirmSlotBookingResponse
	8,  // 10: availability.AvailabilityService.ReleaseHeldSlot:output_type -> availability.ReleaseHeldSlotResponse
	10, // 11: availability.AvailabilityService.GetDoctorAgenda:output_type -> availability.GetDoctorAgendaResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_pb_availability_proto_init() }
func file_pb_availability_proto_init() {
	if File_pb_availability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_availability_proto_rawDesc), len(file_pb_availability_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_availability_proto_goTypes,
		DependencyIndexes: file_pb_availability_proto_depIdxs,
		MessageInfos:      file_pb_availability_proto_msgTypes,
	}.Build()
	File_pb_availability_proto = out.File
	file_pb_availability_proto_goTypes = nil
	file_pb_availability_proto_depIdxs = nil
}
