syntax = "proto3";

package booking_payment;

option go_package = "github.com/MedConnect/booking-service/internal/clients/payment/pb";

message Payment {
  string payment_id = 1;
  string booking_id = 2;
  string user_id = 3;
  double amount = 4;
  string currency = 5;
  string status = 6;
  string created_at = 7;
}

message GetPaymentRequest {
  string payment_id = 1;
}

message GetPaymentResponse {
  Payment payment = 1;
}

service PaymentService {
  rpc GetPayment(GetPaymentRequest) returns (GetPaymentResponse);
}
